// import './scenarios/basic';
// import './scenarios/circular-dependencies';
// import './scenarios/global-module';
// import './scenarios/complete';
// import './scenarios/transient';
// import './scenarios/react';
// import './scenarios/hook-services';
// import './scenarios/guards';
// import './scenarios/event-emitter';
import './scenarios/error-handlers';
